- hosts: localhost
  gather_facts: False
  vars:
    region: us-east-1
    my_ip: 81.137.235.65/32
    ansible_control_sg_id: sg-0b4a8fe0a8042d281
    default_vpc_id: vpc-060f030f6a10fe3b8
  tasks:
    - name: Create security group
      amazon.aws.ec2_security_group:
        name: ansible-test-SG
        description: an example SG created via ansible auto
        vpc_id: "{{ default_vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ my_ip }}"
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ ansible_control_sg_id }}"
        rules_egress:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: group_id

    - name: Print Security Group Id
      debug:
        var: group_id

